import { Injectable } from '@angular/core';
import { Sale } from '../shared/models/sale';

@Injectable({
  providedIn: 'root'
})
export class SalesService {

  constructor() { }
  getsaleById(id:number):Sale{
    return this.getA().find(Sale => Sale.id ==id)!;
  }


  getA():Sale[]{
    return[
      {        
        id:65,
        name:'T-shirt',
        price:45,
        canclledprice:'42 (30% off)',
        favorite:false,
        star:4.5,
        imageUrl:'/assets/me6.jpg',
        tags:['Printed T-shirt','Striped Men'],
        origins:'Italy',
      },
      {
        id:66,
        name:'T-Shirt',
        price:47,
        canclledprice:'45 (20% off)',
        favorite:false,
        star:4.0,
        imageUrl:'/assets/me6.jpg',
        tags:['Flared','Light T-shirt'],
        origins:'India',
      },
      {
        id:67,
        name:'T-Shirt',
        price:49,
        canclledprice:'47 (10% off)',
        favorite:false,
        star:3.5, 
        imageUrl:'/assets/me10.jpg',
        tags:['Plen','Striped men'],
        origins:'China',
      },
      {
        id:68,
        name:'Jeans',
        price:45,
        canclledprice:'42 (20% off)',
        favorite:false,
        star:4.5,
        imageUrl:'/assets/me12 .jpg',
        tags:['Men Jeans','Cotton'],
        origins:'Singapor',
      },
      {
        id:69,
        name:'T-Shirt',
        price:43,
        canclledprice:'39 (30% off)',
        favorite:false,
        star:4.5,
        imageUrl:'/assets/men5.jpg',
        tags:['Plen T-Shirt','Striped Women'],
        origins:'USA',
      },
      {
        id:70,
        name:'Shirt',
        price:41,
        canclledprice:'38 (30% off)',
        favorite:false,
        star:4.5,
        imageUrl:'/assets/me16.jpg',
        tags:['Chex Shirt','Full Slive'],
        origins:'Russia',
      },
      {
        id:71,
        name:'Shirt',
        price:49,
        canclledprice:'48 (10% off)',
        favorite:false,
        star:4,
        imageUrl:'/assets/me1.jpg',
        tags:['Plen Shirt','Striped Men'],
        origins:'India',
      },
      {
        id:72,
        name:'T-Shirt',
        price:42,
        canclledprice:'21 (50% off)',
        favorite:false,
        star:5,
        imageUrl:'/assets/me3.jpg',
        tags:['Plen T-shirt','Cotton'],
        origins:'Franse',
      },
      {
        id:73,
        name:'Jeket',
        price:40,
        canclledprice:'35 (25% off)',
        favorite:false,
        star:4,
        imageUrl:'/assets/me4.jpg',
        tags:['Plen Jeket','Striped Men'],
        origins:'Italy',
      },
      {
        id:74,
        name:'T-shirt',
        price:41,
        canclledprice:'37 (30% off)',
        favorite:false,
        star:4.5,
        imageUrl:'/assets/me18.jpg',
        tags:['Cotton T-Shirt ','Blend'],
        origins:'London',
      },
      {
        id:75,
        name:'Jeket',
        price:49,
        canclledprice:'45 (15% off)',
        favorite:false,
        star:5,
        imageUrl:'/assets/me6.jpg',
        tags:['Cotton','Party Wear'],
        origins:'China',
      },
      {
        id:76,
        name:'Jeans',
        price:45,
        canclledprice:'42 (30% off)',
        favorite:false,
        star:4,
        imageUrl:'/assets/men4.jpg',
        tags:['Slim Jeans','Jeans'],
        origins:'Franse',
      },
      {
        id:77,
        name:'Jeans',
        price:43,
        canclledprice:'42 (10% off)',
        favorite:false,
        star:3.5,
        imageUrl:'/assets/men3.jpg',
        tags:['Slim Jeans','Party Wear'],
        origins:'USA',
      },
      {
        id:78,
        name:'Shirt',
        price:44,
        canclledprice:'42 (20% off)',
        favorite:false,
        star:3,
        imageUrl:'/assets/me9.jpg',
        tags:['Cotton Shirt ','Blend'],
        origins:'India',
      },
      {
        id:79,
        name:'Shirt',
        price:39,
        canclledprice:'35 (30% off)',
        favorite:false,
        star:4.5,
        imageUrl:'/assets/men1.jpg',
        tags:['Casual Shirt','Slim Fit'],
        origins:'Italy',
      },
      {
        id:80,
        name:'T-Shirt',
        price:40,
        canclledprice:'35 (30% off)',
        favorite:false,
        star:4,
        imageUrl:'/assets/men2.jpg',
        tags:['Cotton','Blend'],
        origins:'Franse',
      }
    
    ]
  }
}
